//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advancement
    {
        public Advancement()
        {
            this.Player_Advancement = new HashSet<Player_Advancement>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<Player_Advancement> Player_Advancement { get; set; }
    }
}
