//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dimension
    {
        public Dimension()
        {
            this.Player_Dimension = new HashSet<Player_Dimension>();
            this.World_Dimension = new HashSet<World_Dimension>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Player_Dimension> Player_Dimension { get; set; }
        public virtual ICollection<World_Dimension> World_Dimension { get; set; }
    }
}
