//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Effect
    {
        public Effect()
        {
            this.Player_Effect = new HashSet<Player_Effect>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal duration { get; set; }
    
        public virtual ICollection<Player_Effect> Player_Effect { get; set; }
    }
}
