//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Player
    {
        public int id { get; set; }
        public int inventoryId { get; set; }
        public int playerId { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Player Player { get; set; }
    }
}
