//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory_Item
    {
        public int id { get; set; }
        public Nullable<int> inventoryId { get; set; }
        public Nullable<int> itemId { get; set; }
        public int row { get; set; }
        public int column { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Item Item { get; set; }
    }
}
