//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MinecraftEntities : DbContext
    {
        public MinecraftEntities()
            : base("name=MinecraftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Advancement> Advancement { get; set; }
        public virtual DbSet<Dimension> Dimension { get; set; }
        public virtual DbSet<Effect> Effect { get; set; }
        public virtual DbSet<Inventory> Inventory { get; set; }
        public virtual DbSet<Inventory_Item> Inventory_Item { get; set; }
        public virtual DbSet<Inventory_Player> Inventory_Player { get; set; }
        public virtual DbSet<Item> Item { get; set; }
        public virtual DbSet<Player> Player { get; set; }
        public virtual DbSet<Player_Advancement> Player_Advancement { get; set; }
        public virtual DbSet<Player_Effect> Player_Effect { get; set; }
        public virtual DbSet<Player_Recipe> Player_Recipe { get; set; }
        public virtual DbSet<Recipe> Recipe { get; set; }
        public virtual DbSet<Recipe_Item> Recipe_Item { get; set; }
        public virtual DbSet<Server> Server { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<World> World { get; set; }
        public virtual DbSet<World_Setting> World_Setting { get; set; }
    }
}
