//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public Recipe()
        {
            this.Player_Recipe = new HashSet<Player_Recipe>();
            this.Recipe_Item = new HashSet<Recipe_Item>();
        }
    
        public int id { get; set; }
        public Nullable<int> itemId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ICollection<Player_Recipe> Player_Recipe { get; set; }
        public virtual ICollection<Recipe_Item> Recipe_Item { get; set; }
    }
}
