//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public Setting()
        {
            this.World_Setting = new HashSet<World_Setting>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public bool value { get; set; }
    
        public virtual ICollection<World_Setting> World_Setting { get; set; }
    }
}
