//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class World_Setting
    {
        public int id { get; set; }
        public int worldId { get; set; }
        public int settingId { get; set; }
        public bool value { get; set; }
    
        public virtual Setting Setting { get; set; }
        public virtual World World { get; set; }
    }
}
