//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALMinecraft
{
    using System;
    using System.Collections.Generic;
    
    public partial class World
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public World()
        {
            this.Server = new HashSet<Server>();
            this.World_Dimension = new HashSet<World_Dimension>();
            this.World_Setting = new HashSet<World_Setting>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string seed { get; set; }
        public int difficulty { get; set; }
        public int gamemode { get; set; }
        public bool cheats { get; set; }
        public bool structures { get; set; }
        public int worldType { get; set; }
        public bool bonusChest { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Server> Server { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<World_Dimension> World_Dimension { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<World_Setting> World_Setting { get; set; }
    }
}
